### ISSUE TITLE
Suggestion: Support games that center the cursor

### ISSUE THREAD

**Issue by uRandomAlex** [kuroni/bongocat-osu#1]
Support games that center the cursor every time, i.e. every 3D shooter ever. When mouse reaches the edge of cat's mouse mat the mouse is placed in the center. The mouse should also reset its position after 1 second of inactivity.

It'd also be nice to be able to bind more than 2 keys. There's no need to change the animation - just make 2 config options, one with keys that will trigger the "left click" button animation and other with keys that will trigger the "right click" animation.

**Comment by kuroni** [comment]
I didn't quite understand the configs part, can you explain that more clearly?
Seems interesting but difficult, I will try to implement it ;)

**Comment by uRandomAlex** [comment]
something like this:

```
Key 1: A,W
Key 2: S,D
```

**Comment by kuroni** [comment]
I will add multiple key binds feature in the next release, but tracking auto-centered cursor can take a while ;)

**Comment by kuroni** [comment]
After one week of hard (?) work, we're finally [done](https://github.com/kuroni/bongocat-osu/releases/tag/v1.1.0)!
