### ISSUE TITLE
About Config.json

### ISSUE THREAD

**Issue by IkerCasillasTQ** [kuroni/bongocat-osu#10]
emmm After downloading the file, there are only “img” and “bongocat.exe” in my laptop, and nothing happened after “ctrl + R”,so I don’t know how to set the configuration without finding the “config.json”...could you please tell me the details about how to alter the configuration 😅😅
Please forgive my poor English XD ..Thanks a lot!!

**Comment by kuroni** [comment]
You actually have to create the `config.json` file on your own. First create a file named `config.json` in the same folder as the exe file. [This guide](https://github.com/kuroni/bongocat-osu/wiki/Settings) will help you to add/modify the file for your custom settings.
