### ISSUE TITLE
i dont know where else to ask questions.

### ISSUE THREAD

**Issue by benjiPKS** [kuroni/bongocat-osu#100]
okay so is it possible to make the background transparent or no?

**Comment by peeteer1245** [comment]
That depends on what you want to do with your bongo-cat.

If you want it to be transparent for OBS/Streaming/Videoediting you need to apply a chroma key filter to it and set your background color to a appropreate value.

If you want the window of bongo-cat to be transparent on your desktop you would either need to use a 3rd party tool or program this functionality into bongo-cat yourself.

**Comment by kuroni** [comment]
As suggested by the comment above, it is possible. For example, this is my config:

```json
{
    "decoration": {
        "width": 1920,
        "height": 1080,
        "letterboxing": true,
        "rgb": [0, 255, 0]
    },
    "mode": 2,
    "osu": {
        "key1": [83],
        "key2": [68],
        "smoke": [17],
        "wave": [12]
    },
    "taiko": {
        "leftCentre": [68],
        "rightCentre": [76],
        "leftRim": [83],
        "rightRim": [186]
    }
}
```,

focus on the line `"rgb": [0, 255, 0]`, that changes the background of bongo cat to green. After that, you can basically treat the background as a green screen and apply chroma key filter to your streaming software.
