### ISSUE TITLE
what is the keybind to change it to the tablet

### ISSUE THREAD

**Issue by HacubeMehh** [kuroni/bongocat-osu#104]
whats the tablet key

**Comment by peeteer1245** [comment]
There is no keybind for that as far as I know.
You need to change the value of `mouse` from `true` to `false` in your config.json file.
More information is available in [the wiki](https://github.com/kuroni/bongocat-osu/wiki/Settings).

**Comment by kuroni** [comment]
Hi, please refer to the wiki as the comment above, simply you can just change `mouse` from `true` to `false`.
