### ISSUE TITLE
Space bar key ?

### ISSUE THREAD

**Issue by XeNoXXX54** [kuroni/bongocat-osu#107]
hello, first, nice work this is working so good ! now just a lil thing can we put the space bar into ?

**Comment by peeteer1245** [comment]
Yes! You can use the spacebar as a key.
[The Documentation](https://github.com/kuroni/bongocat-osu/wiki/Settings) describes the way to do it for every mode (search for "key-codes").
If you are using Custom mode you can find a tutorial on it [here](https://github.com/kuroni/bongocat-osu/wiki/Custom-mode).
You can check what key-code your spacebar has [here](https://keycode.info/).

**Comment by kuroni** [comment]
You can surely use space bar as a key referring to the key codes guide. I will close this, but feel free to comment on this thread.
