### ISSUE TITLE
Small question regarding the paw that receives mouse input

### ISSUE THREAD

**Issue by Revv1e** [kuroni/bongocat-osu#108]
Is it possible to personalize that paw more than just changing the color of the fill and outline? If not, will there ever be an update that allows one to use their own drawn up png file for the mouse paw?

btw thank you for this wonderful app

**Comment by peeteer1245** [comment]
No, you currently cannot change anything else.
I recently made #88 wich would allow you to change the start and end position of the mouse hand (meaning the shoulder).
I don't know if @kuroni has any plans for the future regarding that.

**Comment by kuroni** [comment]
I don't have any plans for changing paws in the future, since it is too much work to be done. Best I can do is changing the texture of the paw, but that is also a difficult thing to do.
