### ISSUE TITLE
[help]Adding eye blinking

### ISSUE THREAD

**Issue by WahidIslamLinad** [kuroni/bongocat-osu#112]
Is there any way to add eye blink to the cat..now by any key..like continuous or randomized..(see bongobs if you don't get about the blinking)
Thank you <3

**Comment by WahidIslamLinad** [comment]
I think this can be done by replacing background image with gif format or apng format..but i don't know if it'll support...

**Comment by CSaratakij** [comment]
@WahidIslamLinad No, It's not that simple. SFML doesn't have a built-in sprite animation support. 
You can't simply change the image to .gif and expect it to work.
But it's possible to do, We just have to write our own sprite animation player and make a sprite sheet of the cat blinking.

**Comment by kuroni** [comment]
Hi, it is possible, but I will put this in low priority because I don't want to clutter the code base too much.
