### ISSUE TITLE
how do you make it so that everytime you press a random key, it responds

### ISSUE THREAD

**Issue by B1ackydecatty** [kuroni/bongocat-osu#118]
i just really want to use this for some FPS games but turns out its for rythm games but its fine, its just that i don't know how to map arrow keys and there is four keys in total but i only can modify two and can't add more
sorry if i don't know java well and is really new to programming

**Comment by CSaratakij** [comment]
@B1ackydecatty The key field is actually an array. You can add other key code to it.
like for example : "key1": [90, 65]
See the wiki for other setting [here](https://github.com/kuroni/bongocat-osu/wiki/Settings)

**Comment by B1ackydecatty** [comment]
oh i see! that should make it easier, thank you!

**Comment by B1ackydecatty** [comment]
![image](https://user-images.githubusercontent.com/45589944/103645913-b7f4e980-4f93-11eb-9c82-94848c916f59.png)
i did this instead of that so no wonder

**Comment by B1ackydecatty** [comment]
i guess i will close it now since my question is answered
