### ISSUE TITLE
How can i remove left, right,up and wave png from osu folder?

### ISSUE THREAD

**Issue by Geor-Dan** [kuroni/bongocat-osu#121]
Hi, i wanted to completely remove all the hand that interacts with the keyboard, but if i try to remove the pngs it is unable to stat. Do you have any suggestions in order to fix this?

**Comment by CSaratakij** [comment]
@Geor-Dan Instead of remove pictures, you can replace the one you want to hide with a transparent image. 
Just make sure to use the same file name as the original.

**Comment by Geor-Dan** [comment]
It worked. Thank you very much.
