### ISSUE TITLE
Sorry to interupt but 

### ISSUE THREAD

**Issue by ParadonTaxx** [kuroni/bongocat-osu#125]
how do i add extra keybinds like ( i want to use WASD in my keyboard )
and can you show me a picture on how it looks in the settings ?!?!
and yeah i know i should use [here](https://keycode.info/) KeyCode

**Comment by DattySenpai** [comment]
I don't know a thing about coding but this seemed to work for me 
![image](https://user-images.githubusercontent.com/67298941/106205931-8929f780-617c-11eb-887c-74165eefd8f5.png)

**Comment by kuroni** [comment]
In the `key1` or `key2` value, you can add multiple key codes like this:

```json
...
"key1": [87, 65, 83, 68],
...
```
This produces WASD that is bind to the `key1` slot.

**Comment by ParadonTaxx** [comment]
![image](https://user-images.githubusercontent.com/78140577/106697062-7a699780-65f7-11eb-8afd-a9f174eba0fa.png)

Sorry to interrupt again but i really dont know anything about coding 
and should it look like this ? if yes then it does not work

**Comment by kuroni** [comment]
You need to install the latest release. Check the main page for the download link.

**Comment by ParadonTaxx** [comment]
hey it works !!!!! thanks soo much for your help :D

**Comment by kuroni** [comment]
Nice, I will close this issue then.
