### ISSUE TITLE
No bongo.exe

### ISSUE THREAD

**Issue by acewest** [kuroni/bongocat-osu#13]
So I opened the files in visual studio c++ and found no bongo.exe. If you didnt guess already I'm new to coding and wanted to make it so bongo cat was able to tap the keyboard when I pressed more than 2 buttons. I would love it if someone taught me or made one for me. Thanks!

**Comment by kuroni** [comment]
It's in the [releases](https://github.com/kuroni/bongocat-osu/releases) :D

**Comment by acewest** [comment]
Ohhh thank you!
