### ISSUE TITLE
Making new Binds

### ISSUE THREAD

**Issue by acewest** [kuroni/bongocat-osu#14]
Sorry to bother you again, but how do you add more than two keybinds?

**Comment by kuroni** [comment]
First, check your keycode [here](https://keycode.info/).

After that, you can add multiple values into the fields `key1` and `key2` in the `osu` setting. For example, if you have AS and ZX as your keys, you can do `key1: [65, 90]` and `key2: [83, 88]`.

**Comment by acewest** [comment]
Thanks !

**Comment by brampaard** [comment]
im sorry but where can i find the osu setting

**Comment by MahibGD** [comment]
can i add more than 2 keybind?

**Comment by Dokimochi** [comment]
> can i add more than 2 keybind?

Go to keycode.info and write the keycodes in order in the config. It worked for me.

**Comment by NinjaXGithub** [comment]
how do i add more than 2 keybinds on Bongo Cat V2? i tried with numbers it doesnt work
