### ISSUE TITLE
I don't use Z and X

### ISSUE THREAD

**Issue by Lochie8** [kuroni/bongocat-osu#140]
I use F and G as my keys for osu!. So I would like to know how to change to those keys please.

**Comment by yggdrasilum** [comment]
If you open config.json file in notepad and find osu section with "key1" and "key2" you'll find some numbers in brackets. This are ascii values of the keys you are pressing. In default "key1" is z with 90 value and "key2" is x with 88. For F and G you should change "key1" to 70 and "key2" to 71.

**Comment by Lochie8** [comment]
> If you open config.json file in notepad and find osu section with "key1" and "key2" you'll find some numbers in brackets. This are ascii values of the keys you are pressing. In default "key1" is z with 90 value and "key2" is x with 88. For F and G you should change "key1" to 70 and "key2" to 71.

Thanks. Maybe a thing could be added in for user friendly key changing in the future.
