### ISSUE TITLE
How does this set it?

### ISSUE THREAD

**Issue by StE-Sakurama** [kuroni/bongocat-osu#18]
I touched it for the first time some time ago in BongoCat-osu!, but seem to have a dream because I wanted to do it much more.
But I thought to play in a pen tab, and to change the key setting to be different, but because .txt file enters when it is a past thing, I was able to set it, but it is difficult to change this because there is not it.
I am glad when you can tell how you change it.

Because English is not possible in Japanese, is translation; I'm sorry.

**Comment by StE-Sakurama** [comment]
It was lacking in my confirmation, and Closed had it.
I am sorry that I take trouble.
You may have you delete this contribution.

Thank you！

**Comment by kuroni** [comment]
Thanks for your issue :)
ありがとうございました
