### ISSUE TITLE
stops working when game is in fullscreen

### ISSUE THREAD

**Issue by Klicer** [kuroni/bongocat-osu#19]
the OBS overlay freezes when you have a game in fullscreen. Tried changing process priority, etc nothing fixes. Can't find a solution on google either

EDIT: forgot to mention, I'm running everything in Windows 7 Compability mode

**Comment by Klicer** [comment]
Fixed it by using game capture instead of window capture in OBS

**Comment by C10udCantDev** [comment]
bruh moment it crashed my obs on older version XD

**Comment by C10udCantDev** [comment]
:)
