### ISSUE TITLE
Fullscreen osu!

### ISSUE THREAD

**Issue by Colelin0810** [kuroni/bongocat-osu#2]
the cat doesn't move when i have osu! on fullscreen and i cannot find a solution online please help

**Comment by kuroni** [comment]
If you're using Windows 10, please run both osu! and bongo.exe with Windows 7 Compability mode.

**Comment by uRandomAlex** [comment]
Works fine for me on Windows 10 without compatibility mode.

**Comment by kuroni** [comment]
@uRandomAlex Thank you! I will update the README then.

**Comment by Firemfir** [comment]
> If you're using Windows 10, please run both osu! and bongo.exe with Windows 7 Compability mode.

How do i run osu! and bongo.exe with Windows 7 Compability mode?
