### ISSUE TITLE
The application got crashed when I set "Letterboxing" to true

### ISSUE THREAD

**Issue by raluvy95** [kuroni/bongocat-osu#23]
as the title says.

I used Windows 10 to run Bongo Cat webcam

**Comment by kuroni** [comment]
Sorry for the really late reply, I have been busy recently.

Have you tried setting the app's compability to Windows 7?

**Comment by raluvy95** [comment]
still not worked and I set the app's compability to Windows 7

**Comment by kuroni** [comment]
That is very weird. osu's settings should not affect bongocat's status at anyway.

Which "Letterboxing" are you talking about? osu's settings or the letterboxing option from bongocat?

**Comment by raluvy95** [comment]
the letterboxing option from bongocat

**Comment by kuroni** [comment]
Can you send me the config.json file?

**Comment by raluvy95** [comment]
There's no `config.json` in the folder
![image](https://user-images.githubusercontent.com/43247023/70819591-458cf680-1ddf-11ea-883c-88e0b2839f68.png)

 but I found `settings.txt` (ye, I set the letterboxing to false cuz it won't crash the application)
```txt
=================================================
DO NOT REMOVE ANY SETTINGS, OR CHANGE THEIR ORDER
=================================================

Mouse: true

Key 1 (single capital letter, or number): W
Key 2 (single capital letter, or number): R

Letterboxing: false
osu! x resolution (width): 
osu! y resolution (height): 
Horizontal position (%): 
Vertical position (%): 

mouse.png x offset: 0
mouse.png y offset: 0
mouse.png scalar: 1

tablet.png x offset: 11
tablet.png y offset: -65
tablet.png scalar: 1

Background red: 255
Background green: 255
Background blue: 255```

**Comment by kuroni** [comment]
Oh I see, you are using the original version of bongocat-osu.

Download a new release [here](https://github.com/kuroni/bongocat-osu/releases), check on how to setup [here](https://github.com/kuroni/bongocat-osu/wiki/Settings).

**Comment by Bittersweet1987** [comment]
I cant found the json file :(
![image](https://user-images.githubusercontent.com/56636444/70853694-aedd3a00-1eb1-11ea-97d6-7331e8355743.png)

**Comment by kuroni** [comment]
You create one on your own. If there is no file, bongo will use the default configuration. See more on the wiki I linked above.

**Comment by mozi47** [comment]
Well I want instead of cat I want to replace it yoda. so everything works fine but there is one problem as his left hand the one which he hold the pen. How do I fix that.
https://gyazo.com/09bbb7786aaf4aa7ee45ffd1774797c3

**Comment by raluvy95** [comment]
Thanks, now it's fixed,

**Comment by mozi47** [comment]
can you share the update "exe" file, please?

**Comment by mozi47** [comment]
> Thanks, now it's fixed,

I am still facing the same issue can you share the updated exe file please

**Comment by kuroni** [comment]
You can find it [here](https://github.com/kuroni/bongocat-osu/releases)

**Comment by mozi47** [comment]
> You can find it [here](https://github.com/kuroni/bongocat-osu/releases)
Thank you for the response I check that it has the same problem do you have the update version?
the hand is still not replace: https://gyazo.com/09bbb7786aaf4aa7ee45ffd1774797c3

**Comment by kuroni** [comment]
Sorry, this is not what this issue is about.
Please make a new issue.

**Comment by mozi47** [comment]
> Sorry, this is not what this issue is about.
> Please make a new issue.

ok

**Comment by Myteddycats** [comment]
> Sorry, this is not what this issue is about.
> Please make a new issue.

sir how do i set up to make that cat press the keyboard when i pressing arrow keys
