### ISSUE TITLE
Hardcoding Mouse/Pen Paw Color?

### ISSUE THREAD

**Issue by MacAndSwiss** [kuroni/bongocat-osu#24]
Hello, so I've been fiddling around with the source code for a while trying to figure out how to hardcode in a new paw color. So far, I've been able to modify the color of the edge, but not the fill color itself (so I end up with a different color outline but a white inside). What line(s) should I modify to do so?

I'm assuming that it has to do with the osu.cpp file as that is the only gamemode that actually draws a mouse/pen arm, but I've changed every line referencing "color" without luck. I'm new to C++ and SFML so I'm not familiar with the code.

Thanks for the help!

**Comment by MacAndSwiss** [comment]
Solved. For future reference for everyone else, here are the edits in osu.cpp:

```
// drawing arms
    sf::VertexArray fill(sf::TriangleStrip, 26);
    for (int i = 0; i < 26; i += 2)
    {
        fill[i].position = sf::Vector2f(pss2[i], pss2[i + 1]);
        fill[i + 1].position = sf::Vector2f(pss2[52 - i - 2], pss2[52 - i - 1]);
		//Color Edits?
		fill[i].color = sf::Color(204,153,204,255); //Replace the first 3 values with the RGB of your color, last number is alpha
		fill[i+1].color = sf::Color(204,153,204,255); //Repeat as above
    }
    window.draw(fill);
```

**Comment by kuroni** [comment]
Thank you for the suggestion. Initially, there was such an option, but I deemed it obsolete and remove it. I will add it to the source again.
