### ISSUE TITLE
can't change the mouse lil hand

### ISSUE THREAD

**Issue by pikachubarbudo** [kuroni/bongocat-osu#25]
I changed all the png files and still it wont change, its the hand that holds the mouse

**Comment by kuroni** [comment]
Unfortunately, the paw holding the mouse is drawn by the code and not by the files. Perhaps you want to change its color?

**Comment by Makar8000** [comment]
@kuroni I was about to open a suggestion myself to be able to change the color in the config. I'd like to use a custom cat color but because the hand holding the mouse is White I can't do so :(

**Comment by pikachubarbudo** [comment]
Ohh I see, I'll try that and thank you for the quick answer :]

**Comment by kuroni** [comment]
I added the ability to edit the paw color in the latest release! To use it, add a `paw` subfield into the `osu` field like this:

```json
{
    "osu": {
        "paw": [204, 153, 204]
    }
}
```
Feel free to consult the wiki or ask me for more details!

**Comment by Blazejek2k20** [comment]
> Dodałem możliwość edycji koloru łapy w najnowszej wersji! Aby z niego skorzystać, dodaj `paw`podpole do `osu`pola w następujący sposób:
> 
> ```json
> {
>      " osu " : {
>          " paw " : [ 204 , 153 , 204 ]
>     }
> }
> ```
> 
> Zapraszam do zapoznania się z wiki lub zapytaj mnie o więcej szczegółów!

hi where can i add this because i'm a complete rookie and want to edit bongo cat

**Comment by kuroni** [comment]
For example, this is my config
```json
{
    "mode": 1,
    "resolution": {
        "letterboxing": false,
        "width": 1920,
        "height": 1080,
        "horizontalPosition": 0,
        "verticalPosition": 0
    },
    "decoration": {
        "leftHanded": false,
        "rgb": [255, 255, 255],
        "offsetX": [0, 11],
        "offsetY": [0, -65],
        "scalar": [1.0, 1.0]
    },
    "osu": {
        "mouse": true,
        "toggleSmoke": false,
        "paw": [255, 255, 255], <--
        "pawEdge": [0, 0, 0]
    }
}
```
You put the `paw` section inside the `osu` section like shown (but don't include the arrow like I did).

**Comment by LokiTe** [comment]
Hey! so how do we access to code to change its paw colour?

**Comment by DogeRainbow** [comment]
Can u make a video how to change?

**Comment by Jamongusxd** [comment]
i can edit its appearance? not the colors only?

**Comment by Shad0wongithub** [comment]
> Unfortunately, the paw holding the mouse is drawn by the code and not by the files. Perhaps you want to change its color?

So, provided that you made the Bongo cat thing that has the watermark "Kuvster", can you explain to me how to change the mouse paw color? here's the full layout for that (I already have some settings).

=================================================
DO NOT REMOVE ANY SETTINGS, OR CHANGE THEIR ORDER
=================================================

Mouse: true

Key 1 (single capital letter, or number): W
Key 2 (single capital letter, or number): R

Letterboxing: false
osu! x resolution (width): 
osu! y resolution (height): 
Horizontal position (%): 
Vertical position (%): 

mouse.png x offset: 0
mouse.png y offset: 0
mouse.png scalar: 1

tablet.png x offset: 11
tablet.png y offset: -65
tablet.png scalar: 1

Background red: 62
Background green: 35
Background blue: 110
