### ISSUE TITLE
The hand on mouse is not replacing with the other image.

### ISSUE THREAD

**Issue by mozi47** [kuroni/bongocat-osu#27]
Well I want instead of cat I want to replace it yoda. so everything works fine but there is one problem as his left hand the one which he hold the pen. How do I fix that.
https://gyazo.com/09bbb7786aaf4aa7ee45ffd1774797c3

**Comment by kuroni** [comment]
This feature hasn't been implemented yet :( I will comment when I'm done with it

**Comment by mozi47** [comment]
ok. Thanks.

**Comment by DeoxyShocK** [comment]
Sorry for bothering, but any progress on this feature?

**Comment by mozi47** [comment]
The developer told me he hasnt implement this functionality yet

**Comment by kuroni** [comment]
Hi, I have tried several things, but I can't manage to make this work. Also my free time is incredibly limited, so I don't think I will work on this in the foreseeable future. If anyone wants to make it please do and make a PR for me :(

**Comment by DeoxyShocK** [comment]
Is there a way you could have it replaced with a similar image? The hand I'm trying to get it replaced has a similar shape to Bongo, which might be a bit easier to configure compared to the Yoda hand. Here's an example https://i.imgur.com/2zQd3Rb.png. It's completely fine if you can't do it, thanks for the quick response :)

**Comment by kuroni** [comment]
For that case, you can try setting the paw color, you can see in the wiki [here](https://github.com/kuroni/bongocat-osu/wiki/Settings).

However, if you want to completely change the hand's structure, I don't think I am in the position to do it right now. The curve was drawn completely by code.

**Comment by DeoxyShocK** [comment]
I see; there is no way to change the texture of the curve, like in the paw in that image? What about changing the color of the curve so it's not limited to black? Thanks!

**Comment by kuroni** [comment]
I think I've done it. I will build the package when I have time.

**Comment by DeoxyShocK** [comment]
Alright, thanks!

**Comment by kuroni** [comment]
Can you try the latest release?

**Comment by DeoxyShocK** [comment]
So far so good! I do seem to be having a color problem where if I were to put in (0, 0, 0) it would appear a bit grey-er (lighter of color) than the normal black https://i.imgur.com/Zm81Qb0.jpg. This isn't exactly a huge issue and I could input a color slightly darker than the one I want so I can get the color I need, and if you aren't too busy it would be helpful if you could try and fix the problem, thanks :)

**Comment by kuroni** [comment]
Please check out the new release [here](https://github.com/kuroni/bongocat-osu/releases/tag/v1.4.3.4) :)

**Comment by DeoxyShocK** [comment]
Wow, it worked perfectly! Thanks so much for putting your time into this, is there a place I could donate to appreciate your help?

**Comment by kuroni** [comment]
I don't take donations, but I appreciate that :)

**Comment by DeoxyShocK** [comment]
Alright, thanks a lot :)

**Comment by ChristopherBuilderman** [comment]
Is it possible for you to allow users to change the alpha of the hand? That way if someone wanted to use a different style of hand they could have the option of just putting the hand on the mouse image file and then making the hand that is drawn an alpha of 0.

**Comment by ChristopherBuilderman** [comment]
I think I could do it myself because it seems like it's just hard coded in as 255 right now, but I cannot for the life of me figure out how to actually make changes to the source code and then make my own exe.

**Comment by kuroni** [comment]
I don't have any plans for changing paws in the future, since it is too much work to be done. Best I can do is changing the texture of the paw, but that is also a difficult thing to do.
