### ISSUE TITLE
Suggestion: Third key while playing osu! Standard 

### ISSUE THREAD

**Issue by Pinkuuu** [kuroni/bongocat-osu#3]
I tried adding a third key to have as another picture (like x and z) but for smoke.
Since i thought it would add a lot for my stream seeing how i draw a lot with smoke and me and my chat thought it would be funny if we could make the cat smoke while i drew with smoke (hence i need a third key used for a third image).
This might not be something you see as important, if so i understand you and i will try harder to fix it myself but it's quite hard seeing how i only know c and java 😛 
And if this is something you don't want in the main code i wouldn't mind if you had time and sent me it privately or something (i dont know how github works)

**Comment by kuroni** [comment]
So you'd want a third key for smoke, corresponding to another image (for example smoke.png)?

**Comment by kuroni** [comment]
The release is out! Sorry for the late update.

**Comment by Pinkuuu** [comment]
Its perfect i love it. 
Something i notice tho is that the animated arm (pen/mouse arm) is ontop of the smoke and blunt. But its just so little so probably doesnt matter. Learnt a ton from reading the code changes ty :)

**Comment by kuroni** [comment]
Noted that, it will be fixed in the next release ;)
