### ISSUE TITLE
Aim hand and new keys

### ISSUE THREAD

**Issue by lerralith** [kuroni/bongocat-osu#30]
Hello! could you help me to add a new colour to the aim hand and new keys? I don't know programming ;w; I tried to do it by myself but I don't know how to do it.. Sorry..
I want to add: Q W E R D F 1 2 3 4 
The aim colour hand to be #db3b58 
https://gyazo.com/afbaf01ef3c9cbb6fa85ae30c1d57324
Please!

**Comment by kuroni** [comment]
To which hands do you want to add the keys?

**Comment by lerralith** [comment]
@kuroni so fast :o to the other hand? so there is the mouse hand what i want that colour and the keys to the other hand

**Comment by kuroni** [comment]
Yeah I mean to which finger you want to add the key to? (index finger or middle finger).
I happen to be free right now :)

**Comment by lerralith** [comment]
ummm does it matter? i just want it to move his hands when i press those keys... so.. i think.. index finger? 
https://gyazo.com/210f53779203b0934ac7611ef236df60
Sorry I'm bad at English and at programming

**Comment by lerralith** [comment]
My little slime will be like this anyway
https://gyazo.com/85d3dde2fdd1a541f64c2c811af388e7
So... I know I still need to edit the images but its really cute

**Comment by kuroni** [comment]
Make a new file named `config.json` in the same folder as `bongocat.exe`, then add these lines:

```json
{
    "osu": {
        "mouse": true,
        "paw": [219, 59, 88],
        "key1": [81, 69, 68, 49, 51],
        "key2": [87, 82, 70, 50, 52]
    }
}
```

Hope this helps :)

**Comment by lerralith** [comment]
Umm... thanks but as I said I know nothing at programming.... so its like this? a notepad file?
https://gyazo.com/d6b8f52b6dfab139f95147e5179025b3

**Comment by kuroni** [comment]
Oh I see your trouble lol.

You can try [this tutorial](https://helpdesk.flexradio.com/hc/en-us/articles/204676189-How-to-change-a-File-Extension-in-Windows), and you will see that your current file is actually named `config.json.txt`. Rename that to `config.json` and you are done.

**Comment by lerralith** [comment]
Is still the same.. https://gyazo.com/1412de6b49c08b1eec048a9952a0de0c
I feel so stupid right now

**Comment by kuroni** [comment]
Oh you are still using the old releases lolll. Download a new one [here](https://github.com/kuroni/bongocat-osu/releases/tag/v1.4.3), then copy all of your desired configs/images there. It should work :)

**Comment by lerralith** [comment]
Yeah... It's works! thank you so much! and sorry, i feel so stupid right now ._.

**Comment by kuroni** [comment]
No problem, have fun :)
