### ISSUE TITLE
config.json Won't do anything on bongocat

### ISSUE THREAD

**Issue by Birbatiel** [kuroni/bongocat-osu#34]
I had tried this (blue background) but nothing happened when i did win + r. I'm trying to change the hand color for the mouse. But i'm just testing things, Nothing works. Help.
 {
    "mode": 2,
    "decoration": {
        "rgb": [0, 0, 255]
    }
}

**Comment by kuroni** [comment]
Please do Ctrl + R instead of Win + R. Alternatively, try restarting bongocat.

**Comment by Birbatiel** [comment]
Sorry for the delay, I had tried Ctrl +r, Still nothing. Restarted, nothing. To be correct, i put the config.json in here right? Is it because i'm using v2?
![v2 bongocat config](https://user-images.githubusercontent.com/63872253/79670558-f5a9ac00-8191-11ea-9598-534a7ce00a09.PNG)

**Comment by kuroni** [comment]
Oh, download a new release [here](https://github.com/kuroni/bongocat-osu/releases). The old version is obsolete.

**Comment by Birbatiel** [comment]
Then I create config.json in img > osu correct?

**Comment by kuroni** [comment]
No you put config.json in the same folder as the exe file.

**Comment by Birbatiel** [comment]
Alright, so I put the following code in the config and then started it up, nothing, ctrl + r, nothing...
 {
    "mode": 2,
    "decoration": {
        "rgb": [0, 0, 255]
    }
}

**Comment by Birbatiel** [comment]
Oh nevermind, I was saving it on accident as a txt file.... config.json.txt   Thanks for helping me 👍
