### ISSUE TITLE
can t seem to open your bongo.exe file

### ISSUE THREAD

**Issue by picolojunior** [kuroni/bongocat-osu#38]
I read your wiki but still can not figure out how to open it. Bongo.exe can not open and it let me to choose the program to open that file. Did i miss some programing software to open it?   thank since i really need bongo taigo version so much.

**Comment by kuroni** [comment]
Can you download the latest release [here](https://github.com/kuroni/bongocat-osu/releases/tag/v1.4.3.2) and report to me what it says? Screenshots would be most helpful.

**Comment by picolojunior** [comment]
bro thank so much I download your lastest one and it work now lol also which code in config does modify the background size that really would help me a lot since it is very small screen background now.

**Comment by kuroni** [comment]
You can read on how to modify the config [here](https://github.com/kuroni/bongocat-osu/wiki/Settings).

**Comment by picolojunior** [comment]
bro thank so much for helping and thank for answer me so fast
