### ISSUE TITLE
pawEdge transparency

### ISSUE THREAD

**Issue by EinarKarlJul** [kuroni/bongocat-osu#39]
No matter the RGB value of pawEdge it always ends up slightly transparent.
![Capture](https://user-images.githubusercontent.com/61354402/82745238-570cfe00-9d82-11ea-906f-b3012c808fae.PNG)

**Comment by kuroni** [comment]
Please check out the release [here](https://github.com/kuroni/bongocat-osu/releases/tag/v1.4.3.4). Thanks for reporting!
