### ISSUE TITLE
Suggestion: Making cat wave

### ISSUE THREAD

**Issue by QueenBeelive** [kuroni/bongocat-osu#4]
I thought the addition of the smoke key. It got me thinking what I was missing, then it hit me. Making the cat would be rad, so i implemented it the same way you did for left and right. but using a picture that was like up but a little tilted. I coded it and all but when it came to compiling i was totally lost.
Would be nice to have and easy to implement it, I copied the things you did with left/right and just change it to wave.  Only failed to do it since I don't know how to compile it.
P.S Thanks for all the work it's awesome.

**Comment by kuroni** [comment]
Can you fork can create a PR please?
