### ISSUE TITLE
Assigning mouse click instead of keyboard presses to trigger events

### ISSUE THREAD

**Issue by jellol** [kuroni/bongocat-osu#40]
Is it possible to assign one of paws movement to the mouse like right click, left click or the scroll bar?

**Comment by kuroni** [comment]
Not yet, but this looks like an interesting feature. I will think on how to add this into the program :D

**Comment by jellol** [comment]
> Not yet, but this looks like an interesting feature. I will think on how to add this into the program :D

ovo that would be nice~ i have the tendency to use my mouse's scroll bar/right click/left click more than I do with my keyboard. I don't know anything about coding so I spent time trying to find keycodes for the mouse but there obviously wasn't any LOL. 

Can't wait for if that feature comes, but no rush of course~

**Comment by kuroni** [comment]
Okay based on [this link](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes), you can use 1 for left button and 2 for right button, and I tested and it seems correct. I will update the link in the wiki with this link instead :)

**Comment by jellol** [comment]
> Okay based on [this link](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes), you can use 1 for left button and 2 for right button, and I tested and it seems correct. I will update the link in the wiki with this link instead :) For now, there are no easy scroll wheel detection.

thank you so much!~ Its absolutely what I needed ovo/
