### ISSUE TITLE
Support for other games

### ISSUE THREAD

**Issue by mark905s** [kuroni/bongocat-osu#41]
It would be cool to be able to use the application to stream games such as Valorant. Please consider adding the ability to add other inputs to trigger the keyboard animations! :)

**Comment by kuroni** [comment]
It is already available, you just have to keep adding the inputs in like an array, if that's what you're looking for.

**Comment by mark905s** [comment]
Perfect! I assumed it was never implemented because I just got here from the first reddit post but thanks a bunch for answering!
