### ISSUE TITLE
ico.res missing

### ISSUE THREAD

**Issue by ThePuceMoose** [kuroni/bongocat-osu#42]
Hi,

Make is failing with "[Makefile:24: ico/ico.res] Error 127" when using the given makefile.
 
ico.res appears to be missing from the ico directory.

**Comment by kuroni** [comment]
Oh that probably means you don't have windres available. If that's the case you can edit `bin/bongo.exe: $(OBJ) $(ICO)` into `bin/bongo.exe: $(OBJ)`. Apart from not having the icon for the exe, the compiled program should run normally.

**Comment by ThePuceMoose** [comment]
Fixed this issue, thanks!
