### ISSUE TITLE
bongo cat missing mouse/keyboard/otherarm

### ISSUE THREAD

**Issue by zytumn** [kuroni/bongocat-osu#44]
the overlay is missing the mouse and keyboard and etc etc
https://streamable.com/5327zl
i hope you can help me resolve this, thank you.

**Comment by kuroni** [comment]
Can you try downloading the newest release and verifying whether all images are supposed to be in the `img` folders?

**Comment by zytumn** [comment]
it was a fresh install of the new release

**Comment by kuroni** [comment]
I can't see how this can happen ... Is there an `img` folder in the same location as bongocat.exe, within that there is an `osu` folder, within that there are a lot of image files?

**Comment by zytumn** [comment]
https://streamable.com/bmfzbi
yeah there are the image files. i also just reinstalled visual c++ from windows and restarted

**Comment by kuroni** [comment]
I don't think Visual C++ has anything to do with this issue. Can you try setting other modes (taiko/mania/catch)?

**Comment by zytumn** [comment]
update:i found the fix i had settings in nvidia profile inspector that like fucked opengl. sorry for the trouble
