### ISSUE TITLE
All keys?

### ISSUE THREAD

**Issue by S1monuwu** [kuroni/bongocat-osu#45]
This is more of a request than an issue

I'd love to livestream other games besides Osu! and I think it would be great to be able to add more than 2 keys

I would do it myself but I'm not familiar with c++

**Comment by kuroni** [comment]
It is possible, but also very labor-intensive :( Maybe I will try integrating this in the future

**Comment by S1monuwu** [comment]
Thanks :)

**Comment by picolojunior** [comment]
We just need to bind all key code in the setting right if people want all the key to be blind and it can done manually in the setting.

**Comment by S1monuwu** [comment]
Also, just making the user able to add more that 2 keys by manually putting in key codes in the settings.txt would be enough. :p

**Comment by kuroni** [comment]
That is readily available already. I assume that you're using the first release, we have came a long way from that. Check out the latest release [here](https://github.com/kuroni/bongocat-osu/releases), how to config [here](https://github.com/kuroni/bongocat-osu/wiki/Settings).

**Comment by S1monuwu** [comment]
Are you saying you can add more keys by adding the option "key 3", or "key
4" to the settings file?

**Comment by kuroni** [comment]
No, there are only 2 sprites (key1 and key2), but you can add more keys to activate those two sprites, they work like arrays.

**Comment by S1monuwu** [comment]
Ohhh, thank you so much!

**Comment by kuroni** [comment]
Okay I haven't returned to this for a while.

It is possible now, using `custom` mode in the latest release. The setup will take a while, but it will work.

**Comment by S1monuwu** [comment]
I just added the key codes with the list feture you talked about

**Comment by kuroni** [comment]
Alright. I will close this issue because it seems like it's fixed :) Feel free to reply to this thread in any case, I will try to help out.
