### ISSUE TITLE
i can't add more than 2 keys

### ISSUE THREAD

**Issue by RaiiDoKa** [kuroni/bongocat-osu#49]
how can i add more than 2 binds ? i put one more line and key 3 but the program crashes 
![image](https://user-images.githubusercontent.com/67451455/85819394-eaeb3480-b749-11ea-82dd-af76bf08ea40.png)

**Comment by kuroni** [comment]
Hey, use the latest release [here](https://github.com/kuroni/bongocat-osu/releases/tag/v1.4.3.4), we have long abandoned that version and format.

**Comment by RaiiDoKa** [comment]
oh ok so Ty so much!
