### ISSUE TITLE
Request for arcade stick mode

### ISSUE THREAD

**Issue by mahjongd** [kuroni/bongocat-osu#50]
Was wondering if it would be possible to have an arcade stick mode for fighting games.
8 directions on one paw and 8 buttons on the other
![image](https://user-images.githubusercontent.com/5076751/85953273-7ebf3980-b9b2-11ea-8559-61d730d7d29c.png)

**Comment by kuroni** [comment]
I think it is possible, but this feature will not be in the master branch, since I want to keep the program mainly osu! related.

I will still try to implement it onto a side branch however :)

**Comment by ROMthesheep** [comment]
I was making a hitbox version as a fork, here u go. Its not an .exe tho

https://github.com/ROMthesheep/Arcade-Bongo-Cat

**Comment by kuroni** [comment]
If you can wait, I think I can generalize and allow custom game mode. Is this okay?

**Comment by mahjongd** [comment]
Sounds good boss

**Comment by kuroni** [comment]
The feature is up in this commit https://github.com/kuroni/bongocat-osu/commit/10c74ddba7f3d35f2f3ac008fdaee5387885d475
