### ISSUE TITLE
Feature : Linux native

### ISSUE THREAD

**Issue by CSaratakij** [kuroni/bongocat-osu#55]
I manage to port bongocat-osu to native linux.
Check [this](https://youtu.be/OylY3CnOpKs) out :D
more info : https://github.com/CSaratakij/bongocat-osu/tree/feature-linux-native-port

Actually, I want this to be merge, make a single code base and seperate platform dependent code with a compiler preprocessor. But I don't have Windows right now. So I'm not confident in putting those flag.

If anyone interest in combine this into one single code base, feels free to use my fork as a working linux implementaion :D

**Comment by kuroni** [comment]
Thanks a lot! I will look over this branch over the weekend or next week, since I'm pretty busy right now.

**Comment by kuroni** [comment]
Sorry for the late reply.

I've tested your branch and it seems good, except for that keypresses seem ... sluggish. For example, if I alternately tap X and Z very quickly, then it only displays X being pressed (however, if I start alternating more slowly, then I can see these two keys being pressed).

Is this because your input checking methods?

**Comment by CSaratakij** [comment]
I think this problem is about BONGO_KEYPRESS_THRESHOLD.
I can replicate this problem by setting this to higher value. (from 0.002 to 0.031)
Maybe, try setting it to lower value?
Take a look at [this](https://youtu.be/Ke0OJFKspTc)
Currently, I use SFML for checking the input.
I'm not sure if there is some overhead in SFML.
I'll try to talk to X11 directly for keyboard input if problem still exists.

**Comment by kuroni** [comment]
Okay I actually managed to make it not feel sluggish with BONGO_KEYPRESS_THRESHOLD = 0. Actually, I will see if this can be the general solution for cross-platform input. Thanks a lot for the feedback :)

**Comment by kuroni** [comment]
Ok done

**Comment by TheKaenory** [comment]
Are you considering porting this to Wayland?
