### ISSUE TITLE
Alpha of hand

### ISSUE THREAD

**Issue by ChristopherBuilderman** [kuroni/bongocat-osu#56]
Is it possible for you to allow the user to change the alpha of the hand? I took a look in the source code and it doesn't seem like it would be too difficult. I would do it myself except I am having a lot of trouble running make files or creating the exe in general.

**Comment by kuroni** [comment]
Okay sure :+1: I will try to do this over the weekend

**Comment by kuroni** [comment]
Is up in this commit! https://github.com/kuroni/bongocat-osu/commit/11dd2f46aabe5405de2447770afc3c547cb788be

**Comment by kuroni** [comment]
It's in the latest release now :)

**Comment by ChristopherBuilderman** [comment]
Um see it doesn't really help if you can change the alpha of the hand if you can't change the alpha of the paw edge if, theoretically, you wanted to make the actual drawn hand invisible.

**Comment by kuroni** [comment]
Implemented, sorry for the delay, I've been very busy https://github.com/kuroni/bongocat-osu/commit/edb70927dd7c60677b00301a0532718dfaec969b

**Comment by ChristopherBuilderman** [comment]
Don't worry about it, I only wish I could figure out how to build it myself because it's so simple. Thanks for not only building this but providing continuous development.
