### ISSUE TITLE
Value type error in config.json

### ISSUE THREAD

**Issue by tooruu** [kuroni/bongocat-osu#6]
I get _value type error in config.json_ when opening bongo.exe
How do I fix it?

Contents of config.json:
> {
> 	"mode": 1,
> 	"resolution": {
> 		"letterboxing": true,
> 		"width": 1920,
> 		"height": 1080,
> 		"horizontalPosition": 10,
> 		"verticalPosition": -100
> 	},
> 	"decoration": {
> 		"leftHanded": false,
> 		"rgb": [255, 255, 255],
> 		"offsetX": 10,
> 		"offsetY": -65,
> 		"scalar": [1, 1]
> 	},
> 	"osu": {
> 		"mouse": false,
> 		"key1": [83],
> 		"key2": [68],
> 		"smoke": [70]
> 	}
> }

**Comment by kuroni** [comment]
For the moment, please set your `offsetX` and `offsetY` to arrays of integers. For example:

```json
...
    "offsetX": [0, 10],
    "offsetY": [0, -65],
...
```

fixed problem for me!
