### ISSUE TITLE
Hide mouse paw

### ISSUE THREAD

**Issue by filltiarn** [kuroni/bongocat-osu#62]
Is there a way to easly hide the mouse paw and only leave the mouse?

**Comment by CSaratakij** [comment]
@filltiarn You mean something like [this](https://youtu.be/IsLcsk6BJn4)?
Currently, you can't hide the mouse paw edge.
There is no mouse paw edge alpha setting at the moment.
But this is not hard to implement.
Once we support mouse paw edge alpha setting, we can completely hide the mouse paw.
But we may need to either fill the missing paw by code or just change the background image completely.
As you can see in the screenshot, the mouse background image in "img/osu/mousebg.png" is missing its paw by default.
What do you think? @kuroni 
![bongocat_no_mouse_paw](https://user-images.githubusercontent.com/9628627/88817136-5875ff00-d1e7-11ea-9202-50cf2b33b793.png)

**Comment by filltiarn** [comment]
yup, that's exactly what i wanted, the mouse paw looks a little weird with some custom designs, so this kinda makes it look a Little better

**Comment by kuroni** [comment]
Implemented, sorry for the delay, I've been very busy https://github.com/kuroni/bongocat-osu/commit/edb70927dd7c60677b00301a0532718dfaec969b
