### ISSUE TITLE
How to enable the mouse overlay in the custom mode?

### ISSUE THREAD

**Issue by ddogg26** [kuroni/bongocat-osu#63]
I spent a while looking through the documentation but I could not find a way to enable the mouse in the custom mode.

Am I missing something or has this just not been implemented yet?

**Comment by CSaratakij** [comment]
@ddogg26 Currently, only keyboard support in the custom mode.

**Comment by kuroni** [comment]
Will do

**Comment by Rocksfire** [comment]
Hey,
I actually made a custom mode where you always have a mouse [here](https://github.com/Rocksfire/bongocat-osu).
I just copied code from another file so all credit to [Kuroni](https://github.com/kuroni).
And i design most of the keys for the keyboard :)

**Comment by test512b** [comment]
> Hey,
> I actually made a custom mode where you always have a mouse [here](https://github.com/Rocksfire/bongocat-osu).
> I just copied code from another file so all credit to [Kuroni](https://github.com/kuroni).
> And i design most of the keys for the keyboard :)

thank you so much for making this fork! love you!!

**Comment by Rocksfire** [comment]
> thank you so much for making this fork! love you!!

No probelm ;) ! Hope it's useful :).

**Comment by kuroni** [comment]
@Rocksfire Excuse me, can you make a pull request to this repo? I would love to merge it into the code base. Sorry for not doing a lot since I've been so busy :(

**Comment by Rocksfire** [comment]
@kuroni Yeah no problem, like I said I just copy paste your code. Also, I changed the Readme file to add a link to the releases and I don't know how not to put it in the pull request.

**Comment by kuroni** [comment]
Don't worry about it, I can add more commits after the PR :)

**Comment by Rocksfire** [comment]
Ok. I made the pull request :) much love to you for that awesome bango cat <3

**Comment by kuroni** [comment]
Feature added. Will release later I'm too tired :"(
