### ISSUE TITLE
I'm not able to use it

### ISSUE THREAD

**Issue by theAppleO** [kuroni/bongocat-osu#65]
I tried for hours to turn the folders into an .exe file, but I can't get it working. It's probably just because I don't know how to do it, and because I didn't found any tutorials that worked Im asking it here now.
I'm really not into coding, can someone please help me?

**Comment by CSaratakij** [comment]
@theAppleO You don't have to compile (turn source code into .exe) by yourself.
Just grab our pre-built in our release page [here](https://github.com/kuroni/bongocat-osu/releases) .
Don't grab the source code, choose our build. (x86 is a 32 bit version)
After download, just extract .zip file and run 'bongo.exe'

**Comment by theAppleO** [comment]
Thanks so much, it works perfectly 👍 
Just one thing, I tried to change the Keys, how can I know which key is which number, is there a System behind it?

**Comment by CSaratakij** [comment]
@theAppleO The key number is from the ascii key. You can use [this](https://keycode.info/) to find out.
More info for other setting [here](https://github.com/kuroni/bongocat-osu/wiki/Settings)

**Comment by theAppleO** [comment]
@CSaratakij Thanks for your help, it's so cool
