### ISSUE TITLE
Help running cmake file (file not found)

### ISSUE THREAD

**Issue by RileyTheFox** [kuroni/bongocat-osu#66]
Hi. I don't know much about CMake and Makefiles but when I try and run make I get this error:

`D:\Development\Projects\bongocat-osu>make
g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\SFML\include -Iinclude -L D:\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
process_begin: CreateProcess(NULL, g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\SFML\include -Iinclude -L D:\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [obj/ctb.o] Error 2`

This is my Makefile:
![image](https://user-images.githubusercontent.com/29326764/89952945-1658ae80-dc26-11ea-928b-e292815a8567.png)

I'm on Windows 10. Please help because I don't know a lot about CMake.

**Comment by kuroni** [comment]
Your `LIBFLAGS` should be `-LD:\SFML\lib`.

Oh and try the latest update. I changed a thing or two in the Makefile, specifically the part from `.PHONY` on.

**Comment by RileyTheFox** [comment]
I pulled the new changes and edited the windows Makefile, but I now get this.

`D:\Development\Projects\bongocat-osu>make
mkdir -p obj
mkdir -p bin
A subdirectory or file -p already exists.
Error occurred while processing: -p.
make: *** [create] Error 1`

If I remove -p from the mkdir command, I then get this:
`D:\Development\Projects\bongocat-osu>make
mkdir obj
mkdir bin
g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
process_begin: CreateProcess(NULL, g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [obj/ctb.o] Error 2`

This is the Makefile:
![image](https://user-images.githubusercontent.com/29326764/90010909-99b2e800-dc98-11ea-9b5f-a29a89ea43a0.png)

This is the location of SFML
![image](https://user-images.githubusercontent.com/29326764/90010979-b0f1d580-dc98-11ea-96f9-59390d6e7f7e.png)

**Comment by kuroni** [comment]
Can you manually create the `obj` and `bin` folder in the base directory (so that it is on the same level as `src`, `include, `img`, etc.), comment out the `create` part of your Makefile like this, then retry?
```Makefile
create:
	# mkdir -p $(OBJDIR)
	# mkdir -p bin
```

**Comment by RileyTheFox** [comment]
```
D:\Development\Projects\bongocat-osu>make
# mkdir -p obj
process_begin: CreateProcess(NULL, # mkdir -p obj, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [create] Error 2
```

This is the output now, the create part looks exactly the same as the part you provided. The 2 folders already exist.

**Comment by kuroni** [comment]
Sorry, then can you try delete that part completely? Like this:
```Makefile
create:

test:
 ...
```

**Comment by RileyTheFox** [comment]
After removing the 2 lines in the create part, I now get this:

```
D:\Development\Projects\bongocat-osu>make
g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
process_begin: CreateProcess(NULL, g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [obj/ctb.o] Error 2
```

**Comment by kuroni** [comment]
Can you try this exact comment here on its own without doing `make`: `g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic`?

**Comment by RileyTheFox** [comment]
```
D:\Development\Projects\bongocat-osu>g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
'g++' is not recognized as an internal or external command,
operable program or batch file.
```

Apparently g++ isn't recognised.

**Comment by kuroni** [comment]
Okay nice, refer to [this guide](https://www.rose-hulman.edu/class/csse/resources/MinGW/installation.htm) to get MinGW's binaries recognized.

**Comment by RileyTheFox** [comment]
Should I install mingw from this site? https://sourceforge.net/projects/mingw-w64/
And what settings should I install it with?
![image](https://user-images.githubusercontent.com/29326764/90018624-1fd52b80-dca5-11ea-83cb-37e86ba21e1a.png)
![image](https://user-images.githubusercontent.com/29326764/90018630-2368b280-dca5-11ea-9c98-7e774c66304e.png)
![image](https://user-images.githubusercontent.com/29326764/90018637-25cb0c80-dca5-11ea-8120-482dc09f7a65.png)

The download on the site you linked seems outdated.

**Comment by kuroni** [comment]
The guide I gave you was to help you add `g++` command to be recognized. If you have an installation of MinGW on your computer right now, you should be able to point to that directory. If not, I recommend you download from [here](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/7.3.0/threads-posix/dwarf/i686-7.3.0-release-posix-dwarf-rt_v5-rev0.7z/download), because of #43.

**Comment by RileyTheFox** [comment]
I got mingw installed and recognised (command doesn't work in visual studio code's command prompt though??). Using command prompt in the base directory, I ran the command you wrote above and this is the output:

```
D:\Development\Projects\bongocat-osu>g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\SFML\include -Iinclude -LD:\Development\SFML\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
In file included from src/ctb.cpp:1:0:
include/header.hpp:16:10: fatal error: SFML/Graphics.hpp: No such file or directory
 #include <SFML/Graphics.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by kuroni** [comment]
Can you try doing `D:/Development/SFML` instead of `D:\Development\SFML`? Might work according to #16

**Comment by RileyTheFox** [comment]
Same result
```
D:\Development\Projects\bongocat-osu>g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:/Development/SFML/include -Iinclude -LD:/Development/SFML/lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic
In file included from src/ctb.cpp:1:0:
include/header.hpp:16:10: fatal error: SFML/Graphics.hpp: No such file or directory
 #include <SFML/Graphics.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by kuroni** [comment]
Ah, now that I have noticed your folder, it should look something like this
![image](https://user-images.githubusercontent.com/13513478/90024942-792c6300-dc83-11ea-9c06-84787f018619.png)

**Comment by RileyTheFox** [comment]
This is my SFML folder
![image](https://user-images.githubusercontent.com/29326764/90025864-890d6c80-dcae-11ea-8c88-0ab7b4074ee9.png)

This is the include folder in the project?
![image](https://user-images.githubusercontent.com/29326764/90025894-9165a780-dcae-11ea-8450-64e63773e3b2.png)

**Comment by kuroni** [comment]
No, like you should download the SFML folder as a package from [here](https://www.sfml-dev.org/download/sfml/2.5.1/).

So the comment I sent you linked the header files from D:\Development\SFML\include, and link the compiled library files from D:\Development\SFML\lib, and your folder structure is not correct.

**Comment by RileyTheFox** [comment]
Seems to have worked. I now have a cbt.o file in the obj folder

I dont know which package of SFML I got beforehand but the folder structure for this one is the same as yours.
![image](https://user-images.githubusercontent.com/29326764/90035575-dc38ec80-dcb9-11ea-966d-6ca1a00cca4a.png)

```
D:\Development\Projects\bongocat-osu>g++ -c -o obj/ctb.o src/ctb.cpp -DSFML_STATIC -ID:\Development\libs\SFML-2.5.1\include -Iinclude -LD:\Development\libs\SFML-2.5.1\lib -std=c++17 -s -O2 -mwindows -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -lwinmm -lgdi32 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic

D:\Development\Projects\bongocat-osu>
```

What to do with the .o file now?

**Comment by kuroni** [comment]
You can try running `make` again now

**Comment by RileyTheFox** [comment]
This is what happened https://pastebin.com/6z83d5G4

Also when I run make in VS Code I just get a file not found error. It's because gcc/g++ isn't recognised in VS Code but it is recognised in command prompt. Dont know how to fix that.

**Comment by kuroni** [comment]
Okay that error is easy to fix. You need to download the correct version of SFML library to make it work. In my experience, it's either the SJLJ, SEH, or DW2 version, so give all of them a try.

Remember to do `make clean` then `make` before each compilation with a new library set.

**Comment by RileyTheFox** [comment]
This happens when doing make clean. Seems like it's not been changed to suit Windows
```
D:\Development\Projects\bongocat-osu>make clean
rm  obj/ctb.o  obj/custom.o  obj/data.o  obj/input.o  obj/jsoncpp.o  obj/main.o  obj/mania.o  obj/osu.o  obj/taiko.o || true
'rm' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
make: *** [clean] Error 1
```

I can just delete the files manually though. Just something worth fixing I guess.

It successfully compiled though now. However this is what I get upon opening:
![image](https://user-images.githubusercontent.com/29326764/90042634-d7c50180-dcc2-11ea-86c9-c4eef11651ae.png)

**Comment by kuroni** [comment]
Noted. For you, you need to move the .exe file to the base folder
(alternatively you can do `make test` too)

**Comment by RileyTheFox** [comment]
![image](https://user-images.githubusercontent.com/29326764/90046586-933c6480-dcc8-11ea-8ad5-576cc7faa3cf.png)
This error still occurs in the IDE even though it can compile correctly.

**Comment by kuroni** [comment]
Well that's to be expected. After all, the library is in a different folder.
Since you are using vscode, you might want to see my .vscode/c_cpp_properties.json

```json
{
    "configurations": [
        {
            "name": "mingw-w64",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/kuroni/Documents/Repositories/external_lib/SFML-2.5.1-64bit/include/**"

            ],
            "defines": [],
            "compilerPath": "/usr/bin/x86_64-w64-mingw32-g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

**Comment by RileyTheFox** [comment]
Thanks that fixed it! Is there any way I can setup debugging so I can run it from VS Code?

**Comment by kuroni** [comment]
Uhhhhhh, I don't know really since I always run `make` then test it on the terminal.
