### ISSUE TITLE
release request

### ISSUE THREAD

**Issue by tawli** [kuroni/bongocat-osu#68]
in the issue #62 an user asked to hide the mouse paw of the app, is there a way you can add that option to a release that we can easily toggle it on/off via config.json ?

**Comment by kuroni** [comment]
Hey, it's done! Sorry for making this very long due, but I managed at last.

**Comment by kovacevicit** [comment]
Has anyone been able to use this, I can only hide the pawEdge, what if I want to hide the whole paw?
