### ISSUE TITLE
Excessive GPU usage

### ISSUE THREAD

**Issue by ThisTNTSquid** [kuroni/bongocat-osu#7]
![image](https://user-images.githubusercontent.com/11581624/48277162-2fe72800-e48d-11e8-8bf7-0173868d3f32.png)

**Comment by kuroni** [comment]
Do you happen to know by how does this happened? Or did bongo.exe eat GPU right from its launch?

**Comment by kuroni** [comment]
It seems that I haven't set VSync enabled for the application, and someone else has fixed it.

**Comment by ThisTNTSquid** [comment]
it's ok, I just report it here as eating this much GPU doesn't seem like what it's supposed to be, any thanks for looking into this :)
