### ISSUE TITLE
[osu!] Is it possible to assign key "quote" for key2?

### ISSUE THREAD

**Issue by chmarzyn** [kuroni/bongocat-osu#71]
Like title says I want to assign "quote" for key2, this key have ID number **222**. 
When I change value to "key2": [222], cat's right hand doesn't move at all.
For questioners "Why you want to assign such a weird key" I reply because I'm **left-handed**.

Thank you so much for every answers!

**Comment by kuroni** [comment]
It is, but for some reasons currently it is 34.

I will look into the issue, I think a mistake was made when rewriting the input code

**Comment by CSaratakij** [comment]
Yeah, this is the keycode matching issue by the new input table.
I was looking to the ascii key table instead of [this](https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js#L3) .
That's why the keycode is not exactly match keycode you get from [keycode.info](https://keycode.info/) .

**Comment by CSaratakij** [comment]
@kuroni That's quick~
I was about to fix it myself. LOL~

**Comment by kuroni** [comment]
Ok I rolled out a new release to fix this, sorry for the inconvenience
