### ISSUE TITLE
Now key ID number 59 is not working 

### ISSUE THREAD

**Issue by chmarzyn** [kuroni/bongocat-osu#72]
222 works, now 59 not working. 59 is left side from 222

**Comment by kuroni** [comment]
Are you on Firefox? In [this guide](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes), that key should be 186.

**Comment by chmarzyn** [comment]
> 
> 
> Are you on Firefox? In [this guide](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes), that key should be 186.

I will try and I give you answer

**Comment by chmarzyn** [comment]
> 
> 
> > Are you on Firefox? In [this guide](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes), that key should be 186.
> 
> I will try and I give you answer

Okay everything is working now, I'm sorry for making you trouble.

**Comment by kuroni** [comment]
No problem, have a nice day!
