### ISSUE TITLE
Bongo cat stops working when i minimize the window.

### ISSUE THREAD

**Issue by LogaYT** [kuroni/bongocat-osu#77]
When I try to capture Bongo Cat on Streamlabs and I minimize Bongo Cat window, it stops working and nothing moves, any fix? I tried an other fix that i saw on Issues but anything worked.
Sry if i have bad english xD

**Comment by ChristopherBuilderman** [comment]
Could you try just not minimizing it? Just pull up whatever you are doing over it. That has worked for me.

**Comment by LogaYT** [comment]
Oh it worked xD thanks
