### ISSUE TITLE
Changing mouse hand color

### ISSUE THREAD

**Issue by cshookfung** [kuroni/bongocat-osu#78]
Hi, sorry if this was already answered, but I was wondering how to change the inside color of the mouse hand? When I go into the settings.txt file I cannot find any lines which would allow me to alter that; and I am trying to change the inside color to a yellow to fit with my custom background pngs. Thanks!

**Comment by kuroni** [comment]
I'm so sorry I hadn't been able to answer issues recently. 

Judging by the fact you still have settings.txt, you are still on an early version of the program. Download the latest ones [here](https://github.com/kuroni/bongocat-osu/releases).

**Comment by cshookfung** [comment]
Sorry I hadn't seen that, thank you so much!
