### ISSUE TITLE
Remove the mouse hand

### ISSUE THREAD

**Issue by realthearin** [kuroni/bongocat-osu#81]
is there a way just to remove the right hand entirety?

**Comment by CSaratakij** [comment]
You need to change the "paw" and "pawEdge" alpha to 0

![image](https://user-images.githubusercontent.com/9628627/93371300-5261dd80-f87c-11ea-8690-b376feda4296.png)

**Comment by realthearin** [comment]
ty

**Comment by Tigerpogs** [comment]
What text file are you using to get rid of the arm? I can't manage to find it

**Comment by CSaratakij** [comment]
@Tigerpogs It's a "config.json" file.
It's place in the same directory of the executable if you download from the [release page](https://github.com/kuroni/bongocat-osu/releases) .
See the [wiki](https://github.com/kuroni/bongocat-osu/wiki/Settings) for more info about each setting.
