### ISSUE TITLE
Is there any way to completely delete right hand and arm?

### ISSUE THREAD

**Issue by Tigerpogs** [kuroni/bongocat-osu#82]
I wanted to edit bongo cat to a different character that doesn't really have arms, so I wanted to set an image of the hand on top of the mouse, without the need for an arm connection. I wanted to know if there was a way to remove the right paw, to just have the png with the mouse and hand moving around, without the arm in place.

**Comment by CSaratakij** [comment]
Well, you can set the paw and paw edge alpha to 0 to hide its paw.
See the #81 
But, using the texture with right paw has not implemented.

**Comment by kuroni** [comment]
Sorry trying to clean up here.

Duplicate of #27
