### ISSUE TITLE
Can't use mouse in custom

### ISSUE THREAD

**Issue by mathieuarthur** [kuroni/bongocat-osu#98]
Hi men, I would like to use this as a full cam for stream buuuut, i succeed to attribute all keys of my keyboard to an actions but not to toggle the mouse for custom config, I saw that in your data.cpp you set the default value of mouse for custom on false. I think this override the json file so we can't use mouse with the custom mode.

Kind Regards

**Comment by peeteer1245** [comment]
The default values in `src/data.cpp` get overwritten with your values from `config.json` if they are at the correct position.
Your `config.json` might be malformed, would you mind sharing a unedited version here?
(dont forget to use [codeblocks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting))

**Comment by Trinagan** [comment]
I am having the same issue rn, doing "mouse": true doesn't give you a mouse in the custom mode.

```
 {
    "mode": 5,
    "resolution": {
        "letterboxing": false,
        "width": 1920,
        "height": 1080,
        "horizontalPosition": 0,
        "verticalPosition": 0
    },
    "decoration": {
        "leftHanded": false,
        "rgb": [255, 255, 255],
        "offsetX": [0, 11],
        "offsetY": [0, -65],
        "scalar": [1.0, 1.0]
    },
    "osu": {
        "mouse": true,
        "paw": [255, 255, 255],
        "pawEdge": [0, 0, 0],
        "key1": [90],
        "key2": [88],
        "smoke": [67],
        "wave": [86]
    },
    "taiko": {
        "leftCentre": [88],
        "rightCentre": [67],
        "leftRim": [90],
        "rightRim": [86]
    },
    "catch": {
        "left": [37],
        "right": [39],
        "dash": [16]
    },
    "mania": {
        "4K": true,
        "key4K": [68, 70, 74, 75],
        "key7K": [83, 68, 70, 32, 74, 75, 76]
    },
	"custom": {
		"mouse": true,
		"paw": [255, 255, 255],
		"pawEdge": [0, 0, 0],
		"background": "img/osu/mousebg.png",
		"keyContainers": [
			{
				"defaultImage": "img/osu/up.png",
				"keys":[
				{
					"image": "img/osu/left.png",
					"keyCodes": [81]
				},
				{
					"image": "img/osu/right.png",
					"keyCodes": [87]
				},
				{
					"image": "img/mania/left1.png",
					"keyCodes": [69]
				},
				{
					"image": "img/mania/left2.png",
					"keyCodes": [82]
				},
				{
					"image": "img/osu/wave.png",
					"keyCodes": [67]
				}
				]
			},
			{
				"defaultImage": "img/osu/empty.png",
				"keys":[
			{
					"image": "img/osu/smoke.png",
					"keyCodes": [86]
			}
			]
			}
			]

}
}
```

**Comment by Trinagan** [comment]
I've had a look through the source code, and just realised that custom.cpp doesn't have the mouse support, aka it's just not implemented.

**Comment by peeteer1245** [comment]
In the current Master branch mouse support is definetly supported in custom mode (at least for linux). @kuroni has not yet made a Release that includes that functionality. The latest Release was done on the 13. Aug. and the PR #84 was made on 27. Sep.

It should be possible if you build it yourself from master.

Your JSON does not work with my build because the image for your mouse is missing. The default json from `data.cpp` also does not have a default entry for that. I fixed this in #88 wich is not (yet) merged.  

This is how that should look like:
```json
"custom": {
    "mouse": true,
    "paw": [255, 255, 255],
    "pawEdge": [0, 0, 0],
    "background": "img/osu/mousebg.png",
    "mouseImage": "img/osu/mouse.png",
    "keyContainers": [ "..." ]
}
```

I can provide a Linux binary if you want, but I cannot build for Windows.

Hope this helped.

**Comment by peeteer1245** [comment]
Never mind, I got cross-compiling working.
Here are the Linux and Windows binaries with my own `config.json` that uses custom mode with mouse.
I tested it with wine and on real Windows 10, both work.

[bongocat-osu_win64.zip](https://github.com/kuroni/bongocat-osu/files/5618536/bongocat-osu_win64.zip)
[bongocat-osu_linux64.zip](https://github.com/kuroni/bongocat-osu/files/5618537/bongocat-osu_linux64.zip)

**Comment by Trinagan** [comment]
> Never mind, I got cross-compiling working.
> Here are the Linux and Windows binaries with my own `config.json` that uses custom mode with mouse.
> I tested it with wine and on real Windows 10, both work.
> 
> [bongocat-osu_win64.zip](https://github.com/kuroni/bongocat-osu/files/5618536/bongocat-osu_win64.zip)
> [bongocat-osu_linux64.zip](https://github.com/kuroni/bongocat-osu/files/5618537/bongocat-osu_linux64.zip)

Your config works for me with your executable, but not the latest one from download page

Regardless, the mouse now appears as it should, thanks for you help

**Comment by peeteer1245** [comment]
As I said, the latest release is missing the mouse functionality.

The `config.json` you provided earlier works as long as you add the key `mouseImage` with the value being the path to a image as string.

Happy to be of help <3

**Comment by kuroni** [comment]
Sorry, mouse is now available in `custom` mode now. Really sorry I've been away for a while :(
